ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "SALA"
  site-url: "https://tktran11.github.io/SALA/"
  description: "A suite of tools for analysis and data visualization of actiwatch data."
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/tktran11/SALA/tree/master/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/tktran11/SALA/tree/master/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
