# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/SALA/',
                'doc_host': 'https://tktran11.github.io',
                'git_url': 'https://github.com/tktran11/SALA/tree/master/',
                'lib_path': 'SALA'},
  'syms': {'SALA.plots': {}, 'SALA.processing': {}}}