# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_raw_data": "00_analyze_by_person.ipynb",
         "process_timing_data": "00_analyze_by_person.ipynb",
         "set_sun_timings": "00_analyze_by_person.ipynb",
         "process_sleep_data": "00_analyze_by_person.ipynb"}

modules = ["analyze_by_person.py"]

doc_url = "https://tktran11.github.io/SALA/"

git_url = "https://github.com/tktran11/SALA/tree/master/"

def custom_doc_links(name): return None
