# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SALA": "00_SALA.ipynb",
         "remove_first_day": "00_SALA.ipynb",
         "ClockPlot": "01_plots.ipynb",
         "LightPlot": "01_plots.ipynb"}

modules = ["SALA.py",
           "plots.py"]

doc_url = "https://tktran11.github.io/SALA/"

git_url = "https://github.com/tktran11/SALA/tree/master/"

def custom_doc_links(name): return None
